# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TypingModuleV2
                                 A QGIS plugin
 Модуль набора для проекта по инвентаризации кладбищ. ГеоПланета
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-09
        copyright            : (C) 2018 by Alaxander Semionchik / ГеоПланета
        email                : semionchik.a.g@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TypingModuleV2 class from file TypingModuleV2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .typing_modulev2 import TypingModuleV2
    return TypingModuleV2(iface)
